NAME = libft.a
CC = gcc
CFLAGS = -Wall -Wextra -Werror
INC = -I./inc
SRC_DIR = src
OBJ_DIR = obj

SRCS = $(SRC_DIR)/ft_isalpha.c \
       $(SRC_DIR)/ft_isdigit.c \
       $(SRC_DIR)/ft_isalnum.c \
       $(SRC_DIR)/ft_isascii.c \
       $(SRC_DIR)/ft_isprint.c \
       $(SRC_DIR)/ft_toupper.c \
       $(SRC_DIR)/ft_tolower.c \
       $(SRC_DIR)/ft_strlen.c \
       $(SRC_DIR)/ft_strchr.c \
       $(SRC_DIR)/ft_strrchr.c \
       $(SRC_DIR)/ft_strnstr.c \
       $(SRC_DIR)/ft_strncmp.c \
       $(SRC_DIR)/ft_atoi.c \
       $(SRC_DIR)/ft_calloc.c \
       $(SRC_DIR)/ft_strdup.c \
       $(SRC_DIR)/ft_substr.c \
       $(SRC_DIR)/ft_strjoin.c \
       $(SRC_DIR)/ft_strtrim.c \
       $(SRC_DIR)/ft_split.c \
       $(SRC_DIR)/ft_itoa.c \
       $(SRC_DIR)/ft_strmapi.c \
       $(SRC_DIR)/ft_striteri.c \
       $(SRC_DIR)/ft_putchar_fd.c \
       $(SRC_DIR)/ft_putstr_fd.c \
       $(SRC_DIR)/ft_putendl_fd.c \
       $(SRC_DIR)/ft_putnbr_fd.c \
       $(SRC_DIR)/ft_isspace.c \
       $(SRC_DIR)/ft_strlcpy.c \
       $(SRC_DIR)/ft_strlcat.c \
       $(SRC_DIR)/ft_memset.c \
       $(SRC_DIR)/ft_bzero.c \
       $(SRC_DIR)/ft_memcpy.c \
       $(SRC_DIR)/ft_memmove.c \
       $(SRC_DIR)/ft_lstnew.c \
       $(SRC_DIR)/ft_lstadd_front.c \
       $(SRC_DIR)/ft_lstsize.c \
       $(SRC_DIR)/ft_lstlast.c \
       $(SRC_DIR)/ft_lstadd_back.c \
       $(SRC_DIR)/ft_lstdelone.c \
       $(SRC_DIR)/ft_lstclear.c \
       $(SRC_DIR)/ft_lstiter.c \
       $(SRC_DIR)/ft_lstmap.c

OBJS = $(patsubst $(SRC_DIR)/%.c, $(OBJ_DIR)/%.o, $(SRCS))

all: $(NAME)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $(CFLAGS) $(INC) -c $< -o $@

$(OBJ_DIR):
	test -d $(OBJ_DIR) || mkdir $(OBJ_DIR)

clean:
	rm -rf $(OBJ_DIR)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re


TEST_NAME = test_libft
TEST_SRC = main.c

test: $(NAME) $(TEST_SRC)
	$(CC) $(CFLAGS) $(INC) $(TEST_SRC) $(NAME) -o $(TEST_NAME)

run: test
	./$(TEST_NAME)

clean_test:
	rm -f $(TEST_NAME)

fclean_all: fclean clean_test

.PHONY: test run clean_test fclean_all